### PR TITLE
Pull in tests from PR #3

### PR DESCRIPTION
**Pull request by jeremywiebe**
## Summary:

@jb-1980 created a PR with some great additions to our unit tests. It also had
a conversion to TypeScript which we don't want to tackle at this time, but I
thought the tests were valuable to add. 

Issue: "none"

## Test plan:

`yarn test`

### CODE REVIEW

**Review by jaredly — CHANGES_REQUESTED** [review]
ooh looks like your editors prettier is disagreeing with the prettier you added .. or something like that

**Review by jeresig — APPROVED** [review]
Thanks for adding the tests!

**Review by somewhatabstract — APPROVED** [review]
Always great to see more tests! Thanks for doing this.

**Review by jaredly — APPROVED** [review]
nice

**Pull request merged**
